### GET
GET http://localhost:3002/


### REGISTER

POST http://localhost:3002/users/register 
content-type: application/json

{
"email":"milo11@gmail.com", 
"password": "12345",
"name": "Milo"
}

### LOGIN
POST http://localhost:3002/users/login 
content-type: application/json

{
"email":"milo@gmail.com", 
"password": "12345"
}


### GET USER BY NAME
GET http://localhost:3002/users/Milo
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Il9pZCI6IjY1NWEzMDQ5ODA1MDliZmRjMTQ2ZWY5ZCIsIm5hbWUiOiJNaWxvIiwiZW1haWwiOiJtaWxvQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJFduTjVpNTZmM1N2Ui9LUTZGLlo4NC5wUkxCSHVVdWc1Z0kxdTVmaWNYeUZRbnVjdFo2ZUV1Iiwicm9sZSI6ImFkbWluIiwiX192IjowfSwiaWF0IjoxNzAwNjYwMjE1LCJleHAiOjE3MDMyNTIyMTV9.4G5rgo9Qj__U-jbQnP4KUnDwhhFf9nkD4Yi_t5I_cyk
